### ISSUE TITLE
XML\Team\Senior constructor doesn't work as expected when there are more than 2 teams 

### ISSUE THREAD

**Issue by mindw0rm** [jetwitaussi/PHT#12]
[issue happened with php version 7.0.16]

It seems that $teams is a reference to $this->xml->getElementsByTagName('Teams'), so when a team is removed from $this->xml->getElementsByTagName('Teams'), it gets removed from $teams as well.  As a result, the third team won't get checked/removed. 
As a follow up error (probably one of many?), the flags are not correct, since those of both remaining teams are combined. 

As a workaround, I changed the loops to 
```
for ($t = $teams->length - 1; $t >= 0; $t--) {
 ...
}
```
which seems to do the trick. 

Also, the condition has to be changed to 
`if ($this->xml->getElementsByTagName('Team')->length >= 2)`

**Comment by jetwitaussi** [comment]
Sorry for the delay, i will look at it this week, thanks!
