### ISSUE TITLE
User ID is not set in secondary team HTTeam objects

### ISSUE THREAD

**Issue by SeanDS** [jetwitaussi/PHT#14]
I'm using v2.21, git hash c20774e8abf9c3f357aa6004f8a2176af2d48475.

The problem I get is that if I try to get a user's second and third teams, the user ID is not set in the HTTeam object returned by PHT. This is simple to reproduce - just call `$team = $ht->getSecondaryTeam(1234567, 0)` (second team) or `$team = $ht->getSecondaryTeam(1234567, 1)` (third team), where 1234567 is replaced by a userid with two or three teams, and look at `$team->getUserId()`. The returned value is set to `NULL`. Primary teams, i.e. with `$ht->getPrimaryTeam(1234567)`, seem unaffected.

**Comment by jetwitaussi** [comment]
Due to last MR to handle HTI team, and as i said it does not work for all cases.

**Comment by jetwitaussi** [comment]
Nothing will be done to try to fix this, as it will break other thing
