### ISSUE TITLE
Incompatibility with PHP7

### ISSUE THREAD

**Issue by dpoposki** [jetwitaussi/PHT#7]
Under PHP7 environment, the PHT\Cache\Void and PHT\Log\Void are not valid class names.

> Fatal error: Cannot use 'Void' as class name as it is reserved in PHT/Log/Void.php on line 16

What I would suggest here is that we rename the classes to something like `VoidCache` and `VoidLogger`, although we will introduce a naming inconsistency in the Cache and Log classes. Another suggestion would be to rename all of the classes, i.e. `VoidLogger`, `FileLogger`.

**Comment by jetwitaussi** [comment]
Rename classes to None
